/**
 * Dummy Ad Data for Demo
 * Realistic ad campaigns with variety for testing Max's decision-making
 */

function generateDummyAds() {
  return [
    {
      id: 'ad_tesla_cybertruck_001',
      ad_creative_id: 'ad_tesla_cybertruck_001',
      headline: 'Tesla Cybertruck - The Future is Here',
      body: 'Experience the ultimate electric pickup. Bulletproof exoskeleton, 500+ mile range, 0-60 in 2.9s. Reserve yours today.',
      cta: 'Reserve Now',
      advertiser: {
        name: 'Tesla',
        domain: 'tesla.com',
        qualityRating: 9,
        avgPaid30d: 0.0450,
        accountAge: 180,
      },
      targeting: {
        age: { min: 25, max: 55 },
        interests: ['technology', 'electric vehicles', 'innovation', 'sustainability'],
        income: { min: 75000 },
        countries: ['US', 'UK', 'CA', 'AU', 'DE'],
      },
      metadata: { category: 'Automotive' },
    },
    {
      id: 'ad_rolex_submariner_002',
      ad_creative_id: 'ad_rolex_submariner_002',
      headline: 'Rolex Submariner - Born To Dare',
      body: 'The iconic diver\'s watch. Water resistant to 300m. Swiss precision since 1953. A symbol of achievement.',
      cta: 'Explore Collection',
      advertiser: {
        name: 'Rolex',
        domain: 'rolex.com',
        qualityRating: 10,
        avgPaid30d: 0.0800,
        accountAge: 365,
      },
      targeting: {
        age: { min: 35, max: 65 },
        interests: ['luxury', 'watches', 'status', 'craftsmanship'],
        income: { min: 150000 },
        countries: ['US', 'UK', 'CH', 'HK', 'SG'],
      },
      metadata: { category: 'Luxury Goods' },
    },
    {
      id: 'ad_coinbase_crypto_003',
      ad_creative_id: 'ad_coinbase_crypto_003',
      headline: 'Start Your Crypto Journey with Coinbase',
      body: 'Buy, sell, and manage crypto securely. Get $10 in Bitcoin with your first trade. Trusted by 100M+ users.',
      cta: 'Get Started',
      advertiser: {
        name: 'Coinbase',
        domain: 'coinbase.com',
        qualityRating: 8,
        avgPaid30d: 0.0280,
        accountAge: 90,
      },
      targeting: {
        age: { min: 21, max: 50 },
        interests: ['cryptocurrency', 'finance', 'technology', 'investing'],
        income: { min: 50000 },
        countries: ['US', 'UK', 'CA', 'AU', 'DE', 'FR'],
      },
      metadata: { category: 'Finance' },
    },
    {
      id: 'ad_nike_running_004',
      ad_creative_id: 'ad_nike_running_004',
      headline: 'Nike Air Zoom Pegasus - Run Faster',
      body: 'Responsive cushioning for your daily runs. Engineered for speed and comfort. Free shipping on orders over $50.',
      cta: 'Shop Now',
      advertiser: {
        name: 'Nike',
        domain: 'nike.com',
        qualityRating: 8,
        avgPaid30d: 0.0180,
        accountAge: 200,
      },
      targeting: {
        age: { min: 18, max: 45 },
        interests: ['running', 'fitness', 'sports', 'health'],
        income: { min: 30000 },
        countries: ['US', 'UK', 'CA', 'AU', 'DE', 'FR', 'JP'],
      },
      metadata: { category: 'Athletic Wear' },
    },
    {
      id: 'ad_masterclass_cooking_005',
      ad_creative_id: 'ad_masterclass_cooking_005',
      headline: 'Learn Cooking from Gordon Ramsay',
      body: 'Master culinary techniques from world-renowned chefs. 180+ classes. Annual membership $180. Learn at your own pace.',
      cta: 'Start Learning',
      advertiser: {
        name: 'Masterclass',
        domain: 'masterclass.com',
        qualityRating: 7,
        avgPaid30d: 0.0220,
        accountAge: 120,
      },
      targeting: {
        age: { min: 25, max: 60 },
        interests: ['cooking', 'education', 'culinary arts', 'lifestyle'],
        income: { min: 40000 },
        countries: ['US', 'UK', 'CA', 'AU'],
      },
      metadata: { category: 'Education' },
    },
    {
      id: 'ad_patagonia_fleece_006',
      ad_creative_id: 'ad_patagonia_fleece_006',
      headline: 'Patagonia Better Sweater - Made to Last',
      body: 'Sustainable fleece jacket made from recycled materials. Fair Trade Certified. Free repairs for life.',
      cta: 'Shop Sustainably',
      advertiser: {
        name: 'Patagonia',
        domain: 'patagonia.com',
        qualityRating: 9,
        avgPaid30d: 0.0240,
        accountAge: 150,
      },
      targeting: {
        age: { min: 25, max: 55 },
        interests: ['outdoors', 'hiking', 'sustainability', 'environment'],
        income: { min: 45000 },
        countries: ['US', 'UK', 'CA', 'AU', 'NO', 'SE'],
      },
      metadata: { category: 'Outdoor Apparel' },
    },
    {
      id: 'ad_hellofresh_meals_007',
      ad_creative_id: 'ad_hellofresh_meals_007',
      headline: 'HelloFresh - Fresh Ingredients Delivered',
      body: 'Skip the grocery store. Get pre-portioned ingredients and chef-designed recipes. 50% off your first box!',
      cta: 'Get Discount',
      advertiser: {
        name: 'HelloFresh',
        domain: 'hellofresh.com',
        qualityRating: 6,
        avgPaid30d: 0.0160,
        accountAge: 60,
      },
      targeting: {
        age: { min: 25, max: 50 },
        interests: ['cooking', 'food', 'convenience', 'health'],
        income: { min: 35000 },
        countries: ['US', 'UK', 'CA', 'AU', 'DE'],
      },
      metadata: { category: 'Food Delivery' },
    },
    {
      id: 'ad_headspace_meditation_008',
      ad_creative_id: 'ad_headspace_meditation_008',
      headline: 'Find Your Headspace - Meditation Made Simple',
      body: 'Reduce stress and improve sleep with guided meditations. Try free for 14 days. Science-backed mindfulness.',
      cta: 'Start Free Trial',
      advertiser: {
        name: 'Headspace',
        domain: 'headspace.com',
        qualityRating: 7,
        avgPaid30d: 0.0190,
        accountAge: 110,
      },
      targeting: {
        age: { min: 22, max: 55 },
        interests: ['wellness', 'meditation', 'mental health', 'mindfulness'],
        income: { min: 35000 },
        countries: ['US', 'UK', 'CA', 'AU', 'DE', 'FR'],
      },
      metadata: { category: 'Health & Wellness' },
    },
    {
      id: 'ad_duolingo_spanish_009',
      ad_creative_id: 'ad_duolingo_spanish_009',
      headline: 'Learn Spanish Free with Duolingo',
      body: 'Bite-sized lessons that work. Gamified learning makes it fun. Join 500M learners worldwide. Upgrade to remove ads.',
      cta: 'Download Free',
      advertiser: {
        name: 'Duolingo',
        domain: 'duolingo.com',
        qualityRating: 5,
        avgPaid30d: 0.0075,
        accountAge: 45,
      },
      targeting: {
        age: { min: 16, max: 50 },
        interests: ['language learning', 'education', 'travel', 'culture'],
        income: { min: 20000 },
        countries: ['US', 'UK', 'CA', 'AU', 'DE', 'FR', 'ES', 'MX'],
      },
      metadata: { category: 'Education' },
    },
    {
      id: 'ad_bmw_ix_010',
      ad_creative_id: 'ad_bmw_ix_010',
      headline: 'BMW iX - Electric Luxury Redefined',
      body: 'All-electric SAV with 380 mile range. Ultimate driving pleasure meets zero emissions. Book a test drive.',
      cta: 'Test Drive',
      advertiser: {
        name: 'BMW',
        domain: 'bmw.com',
        qualityRating: 9,
        avgPaid30d: 0.0550,
        accountAge: 220,
      },
      targeting: {
        age: { min: 35, max: 65 },
        interests: ['luxury cars', 'electric vehicles', 'technology', 'performance'],
        income: { min: 100000 },
        countries: ['US', 'UK', 'DE', 'FR', 'CH'],
      },
      metadata: { category: 'Automotive' },
    },
    {
      id: 'ad_monday_productivity_011',
      ad_creative_id: 'ad_monday_productivity_011',
      headline: 'Monday.com - Work Without Limits',
      body: 'Project management that scales with your team. Customizable workflows. 14-day free trial. No credit card required.',
      cta: 'Try Free',
      advertiser: {
        name: 'Monday.com',
        domain: 'monday.com',
        qualityRating: 6,
        avgPaid30d: 0.0140,
        accountAge: 80,
      },
      targeting: {
        age: { min: 25, max: 50 },
        interests: ['productivity', 'business', 'software', 'management'],
        income: { min: 45000 },
        countries: ['US', 'UK', 'CA', 'AU', 'IL'],
      },
      metadata: { category: 'SaaS' },
    },
    {
      id: 'ad_peloton_bike_012',
      ad_creative_id: 'ad_peloton_bike_012',
      headline: 'Peloton Bike+ - Fitness at Home',
      body: 'Live and on-demand classes from world-class instructors. Join the fitness revolution. $400 off limited time.',
      cta: 'Shop Now',
      advertiser: {
        name: 'Peloton',
        domain: 'onepeloton.com',
        qualityRating: 7,
        avgPaid30d: 0.0320,
        accountAge: 140,
      },
      targeting: {
        age: { min: 28, max: 55 },
        interests: ['fitness', 'cycling', 'health', 'home workout'],
        income: { min: 60000 },
        countries: ['US', 'UK', 'CA', 'AU', 'DE'],
      },
      metadata: { category: 'Fitness Equipment' },
    },
  ];
}

// Export for use in extension
if (typeof window !== 'undefined') {
  window.generateDummyAds = generateDummyAds;
}
