-- Migration: Create ad_creative and campaigns tables
-- Date: 2025-11-09
-- Purpose: Store ad creatives (atomic unit for Max evaluation) and campaigns (optional grouping)

-- =====================================================
-- 1. CAMPAIGNS TABLE (optional grouping for advertisers)
-- =====================================================

CREATE TABLE IF NOT EXISTS campaigns (
  id SERIAL PRIMARY KEY,
  campaign_id TEXT UNIQUE NOT NULL,
  advertiser_id TEXT NOT NULL,
  name TEXT NOT NULL,
  total_budget_lamports BIGINT NOT NULL DEFAULT 0,
  spent_lamports BIGINT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed')),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_campaigns_advertiser ON campaigns(advertiser_id);
CREATE INDEX idx_campaigns_status ON campaigns(status);

COMMENT ON TABLE campaigns IS 'Optional grouping for ad_creatives. Used for advertiser reporting and budget management.';
COMMENT ON COLUMN campaigns.campaign_id IS 'Human-readable campaign identifier (e.g., camp_luxury_001)';
COMMENT ON COLUMN campaigns.total_budget_lamports IS 'Total budget allocated for this campaign';
COMMENT ON COLUMN campaigns.spent_lamports IS 'Amount spent so far across all ads in campaign';

-- =====================================================
-- 2. AD_CREATIVE TABLE (atomic unit - what Max evaluates)
-- =====================================================

CREATE TABLE IF NOT EXISTS ad_creative (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ad_creative_id TEXT UNIQUE NOT NULL,
  advertiser_id TEXT NOT NULL,
  campaign_id TEXT REFERENCES campaigns(campaign_id) ON DELETE SET NULL,
  
  -- Ad content
  type TEXT NOT NULL DEFAULT 'text' CHECK (type IN ('text', 'image', 'video', 'html')),
  headline TEXT NOT NULL,
  body TEXT NOT NULL,
  cta TEXT NOT NULL,
  destination_url TEXT NOT NULL,
  
  -- Targeting criteria (JSONB for flexibility)
  targeting JSONB NOT NULL DEFAULT '{}',
  
  -- Budget
  budget_per_impression_lamports BIGINT NOT NULL,
  total_budget_lamports BIGINT NOT NULL,
  spent_lamports BIGINT NOT NULL DEFAULT 0,
  
  -- Privacy-preserving stats (only counters, no individual tracking)
  impressions_count INT NOT NULL DEFAULT 0,
  clicks_count INT NOT NULL DEFAULT 0,
  
  -- Status
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed', 'rejected')),
  
  -- Timestamps
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  
  -- Constraints
  CONSTRAINT valid_budget CHECK (budget_per_impression_lamports > 0),
  CONSTRAINT valid_total_budget CHECK (total_budget_lamports >= budget_per_impression_lamports)
);

CREATE INDEX idx_ad_creative_created_at ON ad_creative(created_at);
CREATE INDEX idx_ad_creative_status ON ad_creative(status);
CREATE INDEX idx_ad_creative_advertiser ON ad_creative(advertiser_id);
CREATE INDEX idx_ad_creative_campaign ON ad_creative(campaign_id);

COMMENT ON TABLE ad_creative IS 'Core table - each row is an atomic unit that Max evaluates. NOT campaigns.';
COMMENT ON COLUMN ad_creative.ad_creative_id IS 'Human-readable ad identifier (e.g., ad_rolex_crypto_001)';
COMMENT ON COLUMN ad_creative.targeting IS 'JSONB: {age: {min, max}, interests: [{category, weight}], income: {min}, location: {countries: []}}';
COMMENT ON COLUMN ad_creative.impressions_count IS 'Privacy-preserving counter (no individual impression records)';
COMMENT ON COLUMN ad_creative.clicks_count IS 'Privacy-preserving counter (no individual click records)';

-- =====================================================
-- 3. UPDATE OFFERS TABLE (add ad_creative_id and zk_proofs)
-- =====================================================

-- Check if ad_creative_id column exists, if not add it
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'offers' AND column_name = 'ad_creative_id'
  ) THEN
    ALTER TABLE offers ADD COLUMN ad_creative_id UUID REFERENCES ad_creative(id) ON DELETE CASCADE;
    CREATE INDEX idx_offers_ad_creative ON offers(ad_creative_id);
  END IF;
END $$;

-- Check if zk_proofs column exists, if not add it
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'offers' AND column_name = 'zk_proofs'
  ) THEN
    ALTER TABLE offers ADD COLUMN zk_proofs JSONB;
  END IF;
END $$;

COMMENT ON COLUMN offers.ad_creative_id IS 'References the specific ad_creative this offer is for';
COMMENT ON COLUMN offers.zk_proofs IS 'ZK-proofs generated by Max: {age: {...}, interests: {...}, income: {...}, location: {...}}';

-- =====================================================
-- 4. TRIGGERS (auto-update timestamps)
-- =====================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_campaigns_updated_at ON campaigns;
CREATE TRIGGER update_campaigns_updated_at
  BEFORE UPDATE ON campaigns
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_ad_creative_updated_at ON ad_creative;
CREATE TRIGGER update_ad_creative_updated_at
  BEFORE UPDATE ON ad_creative
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- MIGRATION COMPLETE
-- =====================================================

-- Verify tables created
SELECT 
  'campaigns' as table_name, 
  COUNT(*) as row_count 
FROM campaigns
UNION ALL
SELECT 
  'ad_creative' as table_name, 
  COUNT(*) as row_count 
FROM ad_creative;
